project_name: etcddump
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io,direct
env_files:
  github_token: ./github.token
before:
  hooks:
    - go mod download
builds:
  - id: "etcddump"
    binary: etcddump
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    flags:
      - -v
      # go1.13
      - -trimpath
    asmflags:
      # use go build -trimpath instead for go1.13
      # - all=-trimpath={{.Env.PWD}}
    gcflags:
      # use go build -trimpath instead for go1.13
      # - all=-trimpath={{.Env.PWD}}
    ldflags:
      - >-
        -s -w
release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  # Note: it can only be one: either github or gitlab or gitea
  github:
    owner: jinmukeji
    name: etcddump
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
